language: python

os: linux

env:
  matrix: 
    - TEST_PACKAGE="pyclaw"
    - TEST_PACKAGE="petclaw"
    - TEST_PACKAGE="forestclaw"

python:
  - 2.7
  - 3.6

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran liblapack-pic
  - sudo apt-get install pv liblapack-dev;
  - git clone --branch=master --depth=100 --quiet git://github.com/clawpack/clawpack
  - cd clawpack
  - git submodule init
  - git submodule update clawutil visclaw riemann
  - rm -rf pyclaw
  - ln -s ../ pyclaw

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
  - conda install python=$TRAVIS_PYTHON_VERSION
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda install -c conda-forge mpich mpi4py
  - conda install matplotlib nose coverage
  - conda install -c clawpack hdf5-parallel h5py-parallel
  - conda install -c conda-forge petsc4py
  - conda install -c conda-forge scipy
  - conda install -c conda-forge python-coveralls
  - python setup.py install

script:
  - cd pyclaw
  - bash ./run_tests_on_travis.sh

after_success:
  - coveralls

notifications:
  email: false
